In [2]:
import pandas as pd 
import numpy as np

In [3]:
df1 = pd.read_csv(r"C:\Users\Siddhi\Desktop\Dataset\loan_data_set.csv",sep=",")
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [5]:
df1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
609    False
610    False
611    False
612    False
613    False
Length: 614, dtype: bool

In [6]:
df1.duplicated().sum()

np.int64(0)

In [10]:
# to delete suplicates
df1 = df1.drop_duplicates()
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [27]:
df1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [13]:
df1.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [15]:
df1["Self_Employed"].mode()

0    No
Name: Self_Employed, dtype: object

In [32]:
# df1["Self_Employed"].fillna("No")
df1["self_Employed"] = df1["Self_Employed"].fillna(df1["Self_Employed"].mode()[0])
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,self_Employeed,self_Employed
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,No,No
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,No,No
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Yes,Yes
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,No,No
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,No,No
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,No,No
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,No,No
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,No,No
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Yes,Yes

In [50]:
df1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History        0
Property_Area         0
Loan_Status           0
self_Employeed        0
self_Employed         0
dtype: int64

In [34]:
df1["Credit_History"].describe()

count    564.000000
mean       0.842199
std        0.364878
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: Credit_History, dtype: float64

In [37]:
x = df1["Credit_History"].astype("object")
x.mode()

0    1.0
Name: Credit_History, dtype: object

In [41]:
df1["Credit_History"] = df1["Credit_History"].fillna(df1["Credit_History"].mode()[0])

In [43]:
df1["LoanAmount"].describe()

count    592.000000
mean     146.412162
std       85.587325
min        9.000000
25%      100.000000
50%      128.000000
75%      168.000000
max      700.000000
Name: LoanAmount, dtype: float64

In [45]:
df1["LoanAmount"] = df1["LoanAmount"].fillna(df1["LoanAmount"].median())

In [47]:
df1["Dependents"].describe()

count     599
unique      4
top         0
freq      345
Name: Dependents, dtype: object

In [48]:
df1["Dependents"].mode()

0    0
Name: Dependents, dtype: object

In [49]:
df1["Dependents"] = df1["Dependents"].fillna(df1["Dependents"].mode()[0])

# Multivariate

# Feature Engineering

In [54]:
# creating new features based on existing columns/features
# create input relationship -> inc efficiency , accuracy , performance
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,self_Employeed,self_Employed
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,No,No
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,No,No
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Yes,Yes
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,No,No
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,No,No
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,No,No
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,No,No
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,No,No
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Yes,Yes

In [57]:
# create total_income of ApplicantIncome + CoapplicantIncome
df1["total_income"] = df1["ApplicantIncome"]+df1["CoapplicantIncome"] # at the end

In [58]:
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,self_Employeed,self_Employed,total_income
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,No,No,5849.0
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,No,No,6091.0
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Yes,Yes,3000.0
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,No,No,4941.0
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,No,No,6000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,No,No,2900.0
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,No,No,4106.0
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,No,No,8312.0
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,No,No,7583.0
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Yes,Yes,4583.0

In [62]:
# loan to income ratio -> total_income how much starting loan i will grant for customer 
# ApplicantIncome more then small amount of loan grant is easy 
# division between loan_amount and total_income
# LTI -> Loan to income ratio

df1["LTI"] = (df1["LoanAmount"]/df1["total_income"])*100
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,self_Employeed,self_Employed,total_income,LTI
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,No,No,5849.0,2.188408
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,No,No,6091.0,2.101461
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Yes,Yes,3000.0,2.200000
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,No,No,4941.0,2.428658
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,No,No,6000.0,2.350000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,No,No,2900.0,2.448276
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,No,No,4106.0,0.974184
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,No,No,8312.0,3.043792
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,No,No,7583.0,2.466042
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Yes,Yes,4583.0,2.902029

In [64]:
df1["total_income"].corr(df1["LoanAmount"])

np.float64(0.6203155389930868)

In [66]:
df1["total_income"].corr(df1["ApplicantIncome"])

np.float64(0.8930372940684422)

In [67]:
df1["LTI"].describe()

count    614.000000
mean       2.387679
std        0.870716
min        0.252292
25%        1.922055
50%        2.412921
75%        2.815802
max        8.271164
Name: LTI, dtype: float64

In [70]:
# create the new feature by binning them into a group 
# binning -> grouping 
# total_income as < 5000 -> low income 
# ti > 5000 and ti < 10000: avg
# ti > 10000: high income 

def income_group(var):
    if var < 5000:
        return "Low income"
    elif var > 5000 and var < 10000:
        return "Mid income"
    else:
        return "High Income"

In [71]:
income_group(500)

'Low income'

In [73]:
df1["binning"] = df1["total_income"].apply(income_group)
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,self_Employeed,self_Employed,total_income,LTI,binning
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,No,No,5849.0,2.188408,Mid income
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,No,No,6091.0,2.101461,Mid income
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Yes,Yes,3000.0,2.200000,Low income
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,No,No,4941.0,2.428658,Low income
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,No,No,6000.0,2.350000,Mid income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,No,No,2900.0,2.448276,Low income
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,No,No,4106.0,0.974184,Low income
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,No,No,8312.0,3.043792,Mid income
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,No,No,7583.0,2.466042,Mid income
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Yes,Yes,4583.0,2.902029,Low income

In [82]:
# create column for stability and unsatbility
# married, edu: graduate & not self-employed -----> stable
# else unstable

def stable(var):
    if (var["Married"] == "Yes") & (var["Education"] == "Graduate") & (var["Self_Employed"] == "No"):
        return "satble"
    else:
        return "unstable"

In [84]:
df1["satbility"] = df1.apply(stable, axis=1)
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,self_Employeed,self_Employed,total_income,LTI,binning,satbility
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,No,No,5849.0,2.188408,Mid income,unstable
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,No,No,6091.0,2.101461,Mid income,satble
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Yes,Yes,3000.0,2.200000,Low income,unstable
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,No,No,4941.0,2.428658,Low income,unstable
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,No,No,6000.0,2.350000,Mid income,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,No,No,2900.0,2.448276,Low income,unstable
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,No,No,4106.0,0.974184,Low income,satble
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,No,No,8312.0,3.043792,Mid income,satble
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,No,No,7583.0,2.466042,Mid income,satble
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Yes,Yes,4583.0,2.902029,Low income,unstable

# Filtering of the data : loc and iloc

### useful for handling huge amount of data 
### useful in memory management -> does not use extra place -> save memory

# loc

### based on column -> considers column
### always used []

In [87]:
# fetch the data of all graduate 
df1.loc[df1["Education"] == "Graduate"]
df1["Education"]

0          Graduate
1          Graduate
2          Graduate
3      Not Graduate
4          Graduate
           ...
609        Graduate
610        Graduate
611        Graduate
612        Graduate
613        Graduate
Name: Education, Length: 614, dtype: object

In [88]:
df1.loc[(df1["Education"] == "Graduate") & (df1["Married"] == "Yes")]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,self_Employeed,self_Employed,total_income,LTI,binning,satbility
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,No,No,6091.0,2.101461,Mid income,satble
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Yes,Yes,3000.0,2.200000,Low income,unstable
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y,Yes,Yes,9613.0,2.777489,Mid income,unstable
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N,No,No,5540.0,2.851986,Mid income,satble
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y,No,No,5532.0,3.036876,Mid income,satble
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y,No,No,5900.0,2.932203,Mid income,satble
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y,No,No,5182.0,2.084137,Mid income,satble
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,No,No,4106.0,0.974184,Low income,satble
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,No,No,8312.0,3.043792,Mid income,satble
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,No,No,7583.0,2.466042,Mid income,satble

# iloc

### workd with the index of columns and row 
### work with both row and column

In [89]:
df1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status',
       'self_Employeed', 'self_Employed', 'total_income', 'LTI', 'binning',
       'satbility'],
      dtype='object')

In [91]:
# To print name along with the index position
# enumerate -> index position of column

for i in enumerate(df1.columns):
    print(i)

(0, 'Loan_ID')
(1, 'Gender')
(2, 'Married')
(3, 'Dependents')
(4, 'Education')
(5, 'Self_Employed')
(6, 'ApplicantIncome')
(7, 'CoapplicantIncome')
(8, 'LoanAmount')
(9, 'Loan_Amount_Term')
(10, 'Credit_History')
(11, 'Property_Area')
(12, 'Loan_Status')
(13, 'self_Employeed')
(14, 'self_Employed')
(15, 'total_income')
(16, 'LTI')
(17, 'binning')
(18, 'satbility')

In [93]:
# slicing using iloc 
df1.iloc[150:201,5:11] # slice the chunk of the data

,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
150,No,6277,0.0,118.0,360.0,0.0
151,Yes,2577,3750.0,152.0,360.0,1.0
152,No,9166,0.0,244.0,360.0,1.0
153,No,2281,0.0,113.0,360.0,1.0
154,No,3254,0.0,50.0,360.0,1.0
155,No,39999,0.0,600.0,180.0,0.0
156,No,6000,0.0,160.0,360.0,1.0
157,No,9538,0.0,187.0,360.0,1.0
158,NaN,2980,2083.0,120.0,360.0,1.0
159,No,4583,5625.0,255.0,360.0,1.0
160,No,1863,1041.0,98.0,360.0,1.0
161,No,7933,0.0,275.0,360.0,1.0
162,No,3089,1280.0,121.0,360.0,0.0
163,No,4167,1447.0,158.0,360.0,1.0
164,No,9323,0.0,75.0,180.0,1.0
165,No,3707,3166.0,182.0,NaN,1.0
166,No,4583,0.0,112.0,360.0,1.0
167,No,2439,3333.0,129.0,360.0,1.0
168,No,2237,0.0,63.0,480.0,0.0
169,No,8000,0.0,200.0,360.0,1.0
170,NaN,1820,1769.0,95.0,360.0,1.0
171,No,51763,0.0,700.0,300.0,1.0
172,No,3522,0.0,81.0,180.0,1.0
173,No,5708,5625.0,187.0,360.0,1.0
174,Yes,4344,736.0,87.0,360.0,1.0
175,No,3497,1964.0,116.0,360.0,1.0
176,No,2045,1619.0,101.0,360.0,1.0
177,No,5516,11300.0,495.0,360.0,0.0
178,No,3750,0.0,116.0,360.0,1.0
179,No,2333,1451.0,102.0,480.0,0.0
180,No,6400,7250.0,180.0,360.0,0.0
181,No,1916,5063.0,67.0,360.0,1.0
182,No,4600,0.0,73.0,180.0,1.0
183,No,33846,0.0,260.0,360.0,1.0
184,No,3625,0.0,108.0,360.0,1.0
185,Yes,39147,4750.0,120.0,360.0,1.0
186,Yes,2178,0.0,66.0,300.0,0.0
187,No,2383,2138.0,58.0,360.0,1.0
188,Yes,674,5296.0,168.0,360.0,1.0
189,No,9328,0.0,188.0,180.0,1.0
190,No,4885,0.0,48.0,360.0,1.0
191,No,12000,0.0,164.0,360.0,1.0
192,No,6033,0.0,160.0,360.0,1.0
193,No,3858,0.0,76.0,360.0,1.0
194,No,4191,0.0,120.0,360.0,1.0
195,No,3125,2583.0,170.0,360.0,1.0
196,No,8333,3750.0,187.0,360.0,1.0
197,No,1907,2365.0,120.0,NaN,1.0
198,No,3416,2816.0,113.0,360.0,1.0
199,Yes,11000,0.0,83.0,360.0,1.0
200,No,2600,2500.0,90.0,360.0,1.0