In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("C:/Users/Siddhi/Desktop/Dataset/drinks.csv")
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,South America
189,Vietnam,111,2,1,2.0,Asia
190,Yemen,6,0,0,0.1,Asia
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [10]:
df.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [9]:
df.tail()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
188,Venezuela,333,100,3,7.7,South America
189,Vietnam,111,2,1,2.0,Asia
190,Yemen,6,0,0,0.1,Asia
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [13]:
# group -> simmilar type of entry come together -> apply it on categorical value 
x = df.groupby("continent")
x.first()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,,
Africa,Algeria,25,0,14,0.7
Asia,Afghanistan,0,0,0,0.0
Europe,Albania,89,132,54,4.9
North America,Antigua & Barbuda,102,128,45,4.9
Oceania,Australia,261,72,212,10.4
South America,Argentina,193,25,221,8.3

In [15]:
x.get_group("Africa")

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
2,Algeria,25,0,14,0.7,Africa
4,Angola,217,57,45,5.9,Africa
18,Benin,34,4,13,1.1,Africa
22,Botswana,173,35,35,5.4,Africa
26,Burkina Faso,25,7,7,4.3,Africa
27,Burundi,88,0,0,6.3,Africa
28,Cote d'Ivoire,37,1,7,4.0,Africa
29,Cabo Verde,144,56,16,4.0,Africa
31,Cameroon,147,1,4,5.8,Africa
33,Central African Republic,17,2,1,1.8,Africa
34,Chad,15,1,1,0.4,Africa
38,Comoros,1,3,1,0.1,Africa
39,Congo,76,1,9,1.7,Africa
47,DR Congo,32,3,1,2.3,Africa
49,Djibouti,15,44,3,1.1,Africa
53,Egypt,6,4,1,0.2,Africa
55,Equatorial Guinea,92,0,233,5.8,Africa
56,Eritrea,18,0,0,0.5,Africa
58,Ethiopia,20,3,0,0.7,Africa
62,Gabon,347,98,59,8.9,Africa
63,Gambia,8,0,1,2.4,Africa
66,Ghana,31,3,10,1.8,Africa
70,Guinea,9,0,2,0.2,Africa
71,Guinea-Bissau,28,31,21,2.5,Africa
88,Kenya,58,22,2,1.8,Africa
95,Lesotho,82,29,0,2.8,Africa
96,Liberia,19,152,2,3.1,Africa
97,Libya,0,0,0,0.0,Africa
100,Madagascar,26,15,4,0.8,Africa
101,Malawi,8,11,1,1.5,Africa
104,Mali,5,1,1,0.6,Africa
107,Mauritania,0,0,0,0.0,Africa
108,Mauritius,98,31,18,2.6,Africa
114,Morocco,12,6,10,0.5,Africa
115,Mozambique,47,18,5,1.3,Africa
117,Namibia,376,3,1,6.8,Africa
123,Niger,3,2,1,0.1,Africa
124,Nigeria,42,5,2,9.1,Africa
142,Rwanda,43,2,0,6.8,Africa
148,Sao Tome & Principe,56,38,140,4.2,Africa
150,Senegal,9,1,7,0.3,Africa
152,Seychelles,157,25,51,4.1,Africa
153,Sierra Leone,25,3,2,6.7,Africa
158,Somalia,0,0,0,0.0,Africa
159,South Africa,225,76,81,8.2,Africa
162,Sudan,8,13,0,1.7,Africa
164,Swaziland,90,2,2,4.7,Africa
172,Togo,36,2,19,1.3,Africa
175,Tunisia,51,3,20,1.3,Africa
179,Uganda,45,9,0,8.3,Africa
183,Tanzania,36,6,1,5.7,Africa
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [17]:
x.get_group("Asia") # group of all entries

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
12,Bahrain,42,63,7,2.0,Asia
13,Bangladesh,0,0,0,0.0,Asia
19,Bhutan,23,0,0,0.4,Asia
24,Brunei,31,2,1,0.6,Asia
30,Cambodia,57,65,1,2.2,Asia
36,China,79,192,8,5.0,Asia
46,North Korea,0,0,0,0.0,Asia
77,India,9,114,0,2.2,Asia
78,Indonesia,5,1,0,0.1,Asia
79,Iran,0,0,0,0.0,Asia
80,Iraq,9,3,0,0.2,Asia
82,Israel,63,69,9,2.5,Asia
85,Japan,77,202,16,7.0,Asia
86,Jordan,6,21,1,0.5,Asia
87,Kazakhstan,124,246,12,6.8,Asia
90,Kuwait,0,0,0,0.0,Asia
91,Kyrgyzstan,31,97,6,2.4,Asia
92,Laos,62,0,123,6.2,Asia
94,Lebanon,20,55,31,1.9,Asia
102,Malaysia,13,4,0,0.3,Asia
103,Maldives,0,0,0,0.0,Asia
112,Mongolia,77,189,8,4.9,Asia
116,Myanmar,5,1,0,0.1,Asia
119,Nepal,5,6,0,0.2,Asia
127,Oman,22,16,1,0.7,Asia
128,Pakistan,0,0,0,0.0,Asia
134,Philippines,71,186,1,4.6,Asia
137,Qatar,1,42,7,0.9,Asia
138,South Korea,140,16,9,9.8,Asia
141,Russian Federation,247,326,73,11.5,Asia
149,Saudi Arabia,0,5,0,0.1,Asia
154,Singapore,60,12,11,1.5,Asia
161,Sri Lanka,16,104,0,2.2,Asia
167,Syria,5,35,16,1.0,Asia
168,Tajikistan,2,15,0,0.3,Asia
169,Thailand,99,258,1,6.4,Asia
171,Timor-Leste,1,1,4,0.1,Asia
176,Turkey,51,22,7,1.4,Asia
177,Turkmenistan,19,71,32,2.2,Asia
181,United Arab Emirates,16,135,5,2.8,Asia
186,Uzbekistan,25,101,8,2.4,Asia
189,Vietnam,111,2,1,2.0,Asia
190,Yemen,6,0,0,0.1,Asia

In [21]:
# group by on the basis of two column
var = df.groupby(["continent","country"]) # write inside the list
var.first()

                            beer_servings  spirit_servings  wine_servings  \
continent     country
Africa        Algeria                  25                0             14
              Angola                  217               57             45
              Benin                    34                4             13
              Botswana                173               35             35
              Burkina Faso             25                7              7
...                                   ...              ...            ...
South America Paraguay                213              117             74
              Peru                    163              160             21
              Suriname                128              178              7
              Uruguay                 115               35            220
              Venezuela               333              100              3

                            total_litres_of_pure_alcohol
continent     country
Africa        Algeria                                0.7
              Angola                                 5.9
              Benin                                  1.1
              Botswana                               5.4
              Burkina Faso                           4.3
...                                                  ...
South America Paraguay                               7.3
              Peru                                   6.1
              Suriname                               5.6
              Uruguay                                6.6
              Venezuela                              7.7

[193 rows x 4 columns]

In [22]:
'''
Aggregate function takes part 
always apply groupby to discrete type of values 
continuous values -> aggregate function
5 types
    sum
    min
    max
    count
    avg
'''

'\nAggregate function takes part \nalways apply groupby to discrete type of values \ncontinuous values -> aggregate function\n5 types\n    sum\n    min\n    max\n    count\n    avg\n'

In [23]:
df.dtypes

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [25]:
# what is the total wine surving for the asia continent

# groupby on continent -> use aggregate function -> .agg({"column_to_apply" : "function_to_apply"})

df.groupby("continent").agg({"wine_servings" : "sum"})

               wine_servings
continent
Africa                   862
Asia                     399
Europe                  6400
North America            564
Oceania                  570
South America            749

In [26]:
# to validate it 
(x.get_group("Asia")).sum()

country                         AfghanistanBahrainBangladeshBhutanBruneiCambod...
beer_servings                                                                1630
spirit_servings                                                              2677
wine_servings                                                                 399
total_litres_of_pure_alcohol                                                 95.5
continent                       AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...
dtype: object

In [27]:
# perform sum of every entry
df.groupby("continent").sum()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,,
Africa,AlgeriaAngolaBeninBotswanaBurkina FasoBurundiC...,3258,866,862,159.4
Asia,AfghanistanBahrainBangladeshBhutanBruneiCambod...,1630,2677,399,95.5
Europe,AlbaniaAndorraArmeniaAustriaAzerbaijanBelarusB...,8720,5965,6400,387.8
North America,Antigua & BarbudaBahamasBarbadosBelizeCanadaCo...,3345,3812,564,137.9
Oceania,AustraliaCook IslandsFijiKiribatiMarshall Isla...,1435,935,570,54.1
South America,ArgentinaBoliviaBrazilChileColombiaEcuadorGuya...,2101,1377,749,75.7

In [28]:
# sum and average of wine_servings together for "Asia" continent

df.groupby("continent").agg({"wine_servings" : ["sum","mean"],"spirit_servings":"min"})

              wine_servings             spirit_servings
                        sum        mean             min
continent
Africa                  862   16.264151               0
Asia                    399    9.068182               0
Europe                 6400  142.222222               0
North America           564   24.521739              68
Oceania                 570   35.625000               0
South America           749   62.416667              25

In [32]:
dt = pd.read_csv("C:/Users/Siddhi/Desktop/Dataset/air_quality_no2_long.csv")
dt

,city,country,date.utc,location,parameter,value,unit
0,Paris,FR,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,µg/m³
1,Paris,FR,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,µg/m³
2,Paris,FR,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,µg/m³
3,Paris,FR,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,µg/m³
4,Paris,FR,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,µg/m³
...,...,...,...,...,...,...,...
2063,London,GB,2019-05-07 06:00:00+00:00,London Westminster,no2,26.0,µg/m³
2064,London,GB,2019-05-07 04:00:00+00:00,London Westminster,no2,16.0,µg/m³
2065,London,GB,2019-05-07 03:00:00+00:00,London Westminster,no2,19.0,µg/m³
2066,London,GB,2019-05-07 02:00:00+00:00,London Westminster,no2,19.0,µg/m³
2067,London,GB,2019-05-07 01:00:00+00:00,London Westminster,no2,23.0,µg/m³

In [34]:
dt.dtypes

city          object
country       object
date.utc      object
location      object
parameter     object
value        float64
unit          object
dtype: object

In [35]:
# change the column name if it in this format -> becz it shows error for dt.date.utc

dt = dt.rename(columns = {"date.utc" : "date_time"})
dt

,city,country,date_time,location,parameter,value,unit
0,Paris,FR,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,µg/m³
1,Paris,FR,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,µg/m³
2,Paris,FR,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,µg/m³
3,Paris,FR,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,µg/m³
4,Paris,FR,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,µg/m³
...,...,...,...,...,...,...,...
2063,London,GB,2019-05-07 06:00:00+00:00,London Westminster,no2,26.0,µg/m³
2064,London,GB,2019-05-07 04:00:00+00:00,London Westminster,no2,16.0,µg/m³
2065,London,GB,2019-05-07 03:00:00+00:00,London Westminster,no2,19.0,µg/m³
2066,London,GB,2019-05-07 02:00:00+00:00,London Westminster,no2,19.0,µg/m³
2067,London,GB,2019-05-07 01:00:00+00:00,London Westminster,no2,23.0,µg/m³

In [36]:
dt.dtypes

city          object
country       object
date_time     object
location      object
parameter     object
value        float64
unit          object
dtype: object

# to_datetime

In [44]:
# Also change the datatype of date_time which is  object to date time

dt["date_time"] = pd.to_datetime(dt["date_time"])
dt.dtypes

# UTC -> time zone for youropian contries

city                      object
country                   object
date_time    datetime64[ns, UTC]
location                  object
parameter                 object
value                    float64
unit                      object
dtype: object

In [45]:
# find minmun amd maximum date 
dt["date_time"].min()

# stores in YY-MM-DD time:Pm/am

Timestamp('2019-05-07 01:00:00+0000', tz='UTC')

In [46]:
dt["date_time"].max()

Timestamp('2019-06-21 00:00:00+0000', tz='UTC')

In [48]:
# what are no. of days or entries covered in this dataset 2019-05-07 to 2019-06-21  
# ans = 44 days

dt["date_time"].max() - dt["date_time"].min()

Timedelta('44 days 23:00:00')

# dt.month -> date month

In [50]:
# extract the months 
# dt.month -> date of month -> to extract month

dt["date_time"].dt.month

0       6
1       6
2       6
3       6
4       6
       ..
2063    5
2064    5
2065    5
2066    5
2067    5
Name: date_time, Length: 2068, dtype: int32

# value_count()

In [52]:
# how many entries do we have for May -> 5th months
dt["date_time"].dt.month.value_counts()

date_time
5    1256
6     812
Name: count, dtype: int64

In [53]:
dt["date_time"].dt.hour

0        0
1       23
2       22
3       21
4       20
        ..
2063     6
2064     4
2065     3
2066     2
2067     1
Name: date_time, Length: 2068, dtype: int32

In [54]:
dt["date_time"].dt.year

0       2019
1       2019
2       2019
3       2019
4       2019
        ...
2063    2019
2064    2019
2065    2019
2066    2019
2067    2019
Name: date_time, Length: 2068, dtype: int32

In [59]:
dt["date_time"].dt.minute

0       0
1       0
2       0
3       0
4       0
       ..
2063    0
2064    0
2065    0
2066    0
2067    0
Name: date_time, Length: 2068, dtype: int32

In [60]:
dt["date_time"].dt.second

0       0
1       0
2       0
3       0
4       0
       ..
2063    0
2064    0
2065    0
2066    0
2067    0
Name: date_time, Length: 2068, dtype: int32

In [61]:
dt["date_time"].dt.weekday

0       4
1       3
2       3
3       3
4       3
       ..
2063    1
2064    1
2065    1
2066    1
2067    1
Name: date_time, Length: 2068, dtype: int32

In [62]:
dt["date_time"]

0      2019-06-21 00:00:00+00:00
1      2019-06-20 23:00:00+00:00
2      2019-06-20 22:00:00+00:00
3      2019-06-20 21:00:00+00:00
4      2019-06-20 20:00:00+00:00
                  ...
2063   2019-05-07 06:00:00+00:00
2064   2019-05-07 04:00:00+00:00
2065   2019-05-07 03:00:00+00:00
2066   2019-05-07 02:00:00+00:00
2067   2019-05-07 01:00:00+00:00
Name: date_time, Length: 2068, dtype: datetime64[ns, UTC]