In [1]:
import pandas as pd

In [13]:
div_1 = pd.DataFrame({"roll_no":[1,2,3,4,5],"First_name":["Tanish","Vaibhav","kundan","Sanjay","Sangeeta"],"Last_name":["X","Y","Z","A","B"],"English":[10,20,30,40,34]})

In [17]:
div_2 = pd.DataFrame({"roll_no":[7,8,9,10],"First_name":["Vai","Kun","San","Saung"],"Last_name":["Y2","Z4","A4","B8"],"Hindi":[56,34,67,12]})

In [15]:
div_1

   roll_no First_name Last_name  English
0        1     Tanish         X       10
1        2    Vaibhav         Y       20
2        3     kundan         Z       30
3        4     Sanjay         A       40
4        5   Sangeeta         B       34

In [16]:
div_2

   roll_no First_name Last_name  Hindi
0        7        Vai        Y2     56
1        8        Kun        Z4     34
2        9        San        A4     67
3       10      Saung        B8     12

In [35]:
div_3 = pd.DataFrame({"roll_no":[1,2,3,4,5],"First_name":["Tanish","Vaibhav","kundan","Sanjay","Sangeeta"],"Last_name":["X","Y","Z","A","B"],"English":[10,20,30,40,34]})
div_3

   roll_no First_name Last_name  English
0        1     Tanish         X       10
1        2    Vaibhav         Y       20
2        3     kundan         Z       30
3        4     Sanjay         A       40
4        5   Sangeeta         B       34

In [50]:
div_4 = pd.DataFrame({"roll_no":[5,8,9,10],"First_name":["Sangeeta","Kun","San","Saung"],"Last_name":["B","Z4","A4","B8"],"Hindi":[56,34,67,12]})
div_4

   roll_no First_name Last_name  Hindi
0        5   Sangeeta         B     56
1        8        Kun        Z4     34
2        9        San        A4     67
3       10      Saung        B8     12

# Concatination

In [51]:
"a"+"b"

'ab'

In [52]:
"b"+"b"

'bb'

In [53]:
# Happens on 2D 
# Decide -> On the basis of what to concatination ? -> rows or column
# based on axis ( 1 -> column and 0 -> rows)

final = pd.concat([div_1,div_2],axis = 0)
final

   roll_no First_name Last_name  English  Hindi
0        1     Tanish         X     10.0    NaN
1        2    Vaibhav         Y     20.0    NaN
2        3     kundan         Z     30.0    NaN
3        4     Sanjay         A     40.0    NaN
4        5   Sangeeta         B     34.0    NaN
0        7        Vai        Y2      NaN   56.0
1        8        Kun        Z4      NaN   34.0
2        9        San        A4      NaN   67.0
3       10      Saung        B8      NaN   12.0

In [54]:
# Problem -> indexing is distrub -> fixing the index
# reset or set the index or fix the index ordering
final = final.reset_index()
final

   index  roll_no First_name Last_name  English  Hindi
0      0        1     Tanish         X     10.0    NaN
1      1        2    Vaibhav         Y     20.0    NaN
2      2        3     kundan         Z     30.0    NaN
3      3        4     Sanjay         A     40.0    NaN
4      4        5   Sangeeta         B     34.0    NaN
5      0        7        Vai        Y2      NaN   56.0
6      1        8        Kun        Z4      NaN   34.0
7      2        9        San        A4      NaN   67.0
8      3       10      Saung        B8      NaN   12.0

In [55]:
final = final.drop("index",axis = 1)
final

   roll_no First_name Last_name  English  Hindi
0        1     Tanish         X     10.0    NaN
1        2    Vaibhav         Y     20.0    NaN
2        3     kundan         Z     30.0    NaN
3        4     Sanjay         A     40.0    NaN
4        5   Sangeeta         B     34.0    NaN
5        7        Vai        Y2      NaN   56.0
6        8        Kun        Z4      NaN   34.0
7        9        San        A4      NaN   67.0
8       10      Saung        B8      NaN   12.0

In [56]:
# x_1 = x_1.set_index("roll_no") # roll number becomes index
# x_1

# Merging

In [57]:
# having entries of multiple types
div_3

   roll_no First_name Last_name  English
0        1     Tanish         X       10
1        2    Vaibhav         Y       20
2        3     kundan         Z       30
3        4     Sanjay         A       40
4        5   Sangeeta         B       34

In [58]:
div_4

   roll_no First_name Last_name  Hindi
0        5   Sangeeta         B     56
1        8        Kun        Z4     34
2        9        San        A4     67
3       10      Saung        B8     12

In [59]:
# Sangeeta gives both exams english and hindi
pd.concat([div_3,div_4], axis = 0) # creating reducdancy

   roll_no First_name Last_name  English  Hindi
0        1     Tanish         X     10.0    NaN
1        2    Vaibhav         Y     20.0    NaN
2        3     kundan         Z     30.0    NaN
3        4     Sanjay         A     40.0    NaN
4        5   Sangeeta         B     34.0    NaN
0        5   Sangeeta         B      NaN   56.0
1        8        Kun        Z4      NaN   34.0
2        9        San        A4      NaN   67.0
3       10      Saung        B8      NaN   12.0

In [60]:
# Merging

# avoid duplicate entry
# uses Joins -> joins two datasets 
# types :-  left -> column 1 with common entry
#           right -> column 2 with common entry
#           inner -> only common entry 
#           outer -> common entry only one time with all entry of column 1 and column 2
# common entry -> sangeeta
# outer is suitable for us

In [61]:
merged_df = pd.merge(div_3, div_4, on=["roll_no","First_name","Last_name"], how="outer")
merged_df

   roll_no First_name Last_name  English  Hindi
0        1     Tanish         X     10.0    NaN
1        2    Vaibhav         Y     20.0    NaN
2        3     kundan         Z     30.0    NaN
3        4     Sanjay         A     40.0    NaN
4        5   Sangeeta         B     34.0   56.0
5        8        Kun        Z4      NaN   34.0
6        9        San        A4      NaN   67.0
7       10      Saung        B8      NaN   12.0